name: ci
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Format check
        run: deno fmt --check
      - name: Lint
        run: deno lint
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Test
        run: deno test
